### ISSUE TITLE
Recipe Project

### ISSUE THREAD

**Issue by barakadanny** [barakadanny/Recipe-app#10]
# Note 🔖 
This project is being developed by:
-  [Baraka Danny](https://github.com/barakadanny) 
- [Muskan](https://github.com/muskan2532150) 

Link to the Project distribution  [Kanban board](https://github.com/users/barakadanny/projects/4/views/1)

Happy Coding 🥂

**Comment by prolajumokeoni** [comment]
Hi @Team
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  does not have a GitHub project setup (kanban board), please follow the project requirement to create your Github [project ](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by barakadanny** [comment]
@prolajumokeoni 
Thank you for the feedback,
The project kanban board was provided via the link. 
Here it is again
[Kanban board](https://github.com/users/barakadanny/projects/4/views/1)

**Comment by prolajumokeoni** [comment]
Hi when I clicked the link this is what I saw, please check and make sure that your kanban board is accessible and can be viewed 
![Screenshot_581](https://user-images.githubusercontent.com/69638013/210215841-7334c0d4-5a3e-477b-8b42-dfa34c1b07cb.png)

**Comment by barakadanny** [comment]
@prolajumokeoni 
solved, it was private

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @barakadanny & @muskan2532150, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All requirements completed

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
